# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: gnu gcc version cmd.exe
      shell: cmd
      run: |
        c:\msys64\mingw32\bin\gcc -v --version
    
    - name: gnu gcc version bash
      shell: bash
      run: |
        set -x
        /c/msys64/mingw32/bin/gcc -v --version
    
    - name: gnu gcc compile
      shell: bash
      run: |
        set -x
        /c/msys64/mingw32/bin/gcc -v hello.c -o hello
        ls -la
        ./hello.exe
    
    - name: mingw gcc versions
      shell: bash
      run: |
        set -x
        //c/msys64/mingw32/bin/i686-w64-mingw32-gcc -v --version
