# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: show disk info
      run: |
        # diskutil info -all
        ls -la /usr/local/opt/runner/settings/instancename
        cat /usr/local/opt/runner/settings/instancename/*
    
    - name: build mksparse
      run: |
        ls -lsa
        gcc mksparse.c -o mksparse
        ./mksparse 
        ls -ls
        mv file.hole /tmp/f.hole
        mv file.nohole /tmp/f.nohole
        ls -ls /tmp/f.*
        mkdir /tmp/work
        cp mksparse /tmp/work
        cd /tmp/work
        ./mksparse 
        ls -ls

    - name: tar
      run: |
        cd /tmp/work
        for i in {1..100}; do
           echo "Attempt $i"
           test -f /tmp/bin1 && rm /tmp/bin1
           #dd if=/dev/random of=/tmp/bin1 bs=1k seek=1024 count=10
           test -f file.hole && rm file.hole
           ./mksparse 
           mv file.hole /tmp/bin1
           test -f file.hole && rm file.hole
           ./mksparse 
           mv file.hole /tmp/bin2
           test -f /tmp/bin2 && rm /tmp/bin2
           #dd if=/dev/random of=/tmp/bin2 bs=1k seek=1024 count=10
           echo "files to tar:"
           ls -ls /tmp/bin?
           shasum /tmp/bin1 /tmp/bin2 > /tmp/check
           tar  -czvf /tmp/arc.tgz /tmp/bin1 /tmp/bin2
           mkdir /tmp/x
           pushd /tmp/x
           tar -xvzf /tmp/arc.tgz
           echo "untarred files:"
           cd tmp
           ls -ls
           shasum -c /tmp/check || exit 1
           popd
           rm -rf /tmp/x
        done



