# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        #        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    
    runs-on: ${{ matrix.os }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: setup llvm repos
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 10
        sudo ./llvm.sh 11
        sudo ./llvm.sh 12
    
    - name: move llvm repos
      run: |
        grep apt.llvm.org/focal /etc/apt/sources.list| sudo tee /etc/apt/sources.list.d/llvm.list
        sudo sed -i'' -e /apt.llvm.org/d /etc/apt/sources.list
        echo "Update"
        sudo apt-get update
        
    - name: use llvm repos
      run: |
        sudo apt-get install aptitude
        sudo aptitude install -y libc++-12-dev libc++abi-12-dev

