# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: make changes
      run: |
        #strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep "GLIBCXX"
        #grep GLIBCXX_3.4.29 -l /usr/lib/x86_64-linux-gnu/*
        ls -la /usr/lib/x86_64-linux-gnu/libstdc++*
        # dpkg -S  /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29
        # apt-cache showpkg libstdc++6:amd64
        ls -la `which gcc`
        ls -la `which gcc-10`
        ls -la `which gcc-11`
        sudo apt-get -y purge g++-11
        sudo apt-get -y purge g++-10
        sudo apt-get -y purge g++-9
        sudo apt-get -y purge libstdc++6 || true
        ls -la /usr/lib/x86_64-linux-gnu/libstdc++*
        #strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep "GLIBCXX"
        sudo apt-get -y install g++-9
        ls -la /usr/lib/x86_64-linux-gnu/libstdc++*
        strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep "GLIBCXX"

