# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: default
      run: |
        echo on
        echo %HOME%
    
    - name: cmd
      shell: cmd
      run: |
        echo on
        echo %HOME%
        echo %USERPROFILE%
        echo  %HOMEDRIVE%%HOMEPATH%
    
    - name: bash
      shell: bash
      run: |
        echo $HOME
    
    - name: pwsh echo
      shell: pwsh
      run: |
        echo $env:HOME
        echo $env:USERPROFILE
        echo "${env:HOMEDRIVE}${env:HOMEPATH}"
    
    - name: pwsh write host
      shell: pwsh
      run: |
        Write-Host $env:HOME
        Write-Host $env:USERPROFILE
        Write-Host "${env:HOMEDRIVE}${env:HOMEPATH}"

