# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: ndk copy
      run: |
          copy ndk.cmd "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk.cmd"
          copy ndk-test.cmd "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-test.cmd"

    - name: ndk test
      run: |
        Get-Content "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk.cmd"
        & "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk.cmd"
      shell: powershell

    - name: ndk test with params
      run: |
        Get-Content "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk.cmd"
        & "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk.cmd" aaa bbb
      shell: powershell
    
    - name: ndk-build
      run: |
        Get-Content "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd"
        & "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\ndk-build.cmd"
      shell: powershell

