# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: describe cmake 3.20.5
      run: |
        ls -la $(which cmake)
        cmake --version
        echo $CMAKE_ROOT
        ls -l /usr/local/share
        
    - name: disable cmake 3.20.5
      run: |
        echo "chmod -x $(which cmake)"
        sudo chmod -x $(which cmake)
        echo "cmake --version"
        cmake --version || echo "Can't run"
        echo "hash -l"
        hash -l
        echo "hash -r"
        hash -r
        echo "cmake --version"
        cmake --version
        
    - name: another step
      run: |
        echo "cmake --version"
        cmake --version
        echo "hash -l"
        hash -l
        echo "hash -r"
        hash -r
        echo "cmake --version"
        cmake --version
