name: CI

on: [push]
    
jobs:
  build:
    runs-on: macos-10.15

    strategy:
      matrix:
        os: [ macos-10.15 ]
        cxx: [ g++-9 ]
        build_type: [ Debug, Release ]

    
    steps:
    - name: which CXX
      run: |
        which ${{matrix.cxx}} 
        ${{matrix.cxx}} --version

    - uses: actions/checkout@v2

    - name: mkdir build
      run: mkdir build

    - name: cmake
      run: cmake -D CMAKE_CXX_COMPILER=`which ${{matrix.cxx}}` -D CMAKE_BUILD_TYPE=${{matrix.build_type}} ..  
      working-directory: ./build

    - name: make
      run: make -j2 VERBOSE=1
      working-directory: ./build
