# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

env:
  # Please ensure that this is in sync with graalVersion in build.sbt
  graalVersion: 21.1.0
  # Please ensure that this is in sync with javaVersion in build.sbt
  javaVersion: 11
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    #- name: Setup GraalVM Environment
    #  uses: ayltai/setup-graalvm@v1
    #  with:
    #    graalvm-version: ${{ env.graalVersion }}
    #    java-version: ${{ env.javaVersion }}
    #    native-image: true
    
    - name: find mspdbcore.dll
      run: |
        Get-ChildItem -Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\" -Filter mspdbcore.dll -Recurse -ErrorAction SilentlyContinue -Force
        
    - name: copy mspdbcore.dll to LIBPATH
      run: |
        copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\Hostx86\x86\mspdbcore.dll" "~\mspdbcore.dll"          
      
