# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: osx-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: make changes
      run: |
        set -x
        dd of=/tmp/bin1 bs=10M seek=1 count=0
        ls -la /tmp/bin1
        dd of=/tmp/bin2 bs=10M seek=1 count=0
        ls -la /tmp/bin2
        shasum /tmp/bin1 /tmp/bin2 > /tmp/check
        tar  -cvf /tmp/arc.tar /tmp/bin1 /tmp/bin2
        mkdir /tmp/x
        pushd /tmp/x
        tar -xf /tmp/arc.tar
        shasum -c /tmp/check || exit
        popd
        rm -rf /tmp/x




