# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows:
    # The type of runner that the job will run on
    runs-on: windows-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Build
      shell: pwsh 
      run: |
        $ErrorView = 'NormalView'
        $installPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version 16.0 -property installationpath
        $instanceId = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version 16.0 -property instanceid
        Import-Module "$installPath\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Write-Host "ip=$installPath"
        Write-Host "id=$installId"
        Enter-VsDevShell $instanceId
        msbuild --version





