# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

env:
  # Please ensure that this is in sync with graalVersion in build.sbt
  graalVersion: 21.1.0
  # Please ensure that this is in sync with javaVersion in build.sbt
  javaVersion: 11
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    #- name: Setup GraalVM Environment
    #  uses: ayltai/setup-graalvm@v1
    #  with:
    #    graalvm-version: ${{ env.graalVersion }}
    #    java-version: ${{ env.javaVersion }}
    #    native-image: true
    
    - name: rebar3 update
      run: |
        rebar3 update
    
    - name: rebar3 compile
      run: |
        rebar3 compile
