# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: ./.github/actions/download-qt
      with:
        toolchain: win64_msvc2019_64
#    - name: Install Qt Creator
#      uses: ./.github/actions/download-qtc
#    - name: Setup Qbs
#      run: |
#        qbs setup-toolchains --detect
#        qbs setup-qt $(which qmake).exe qt
#        qbs config defaultProfile qt
#        qbs config --list
#      shell: bash
##    - name: prepare timestamp
##      id: get-timestamp
##      run: echo ::set-output name=timestamp::$(date -u +"%Y-%m-%dT%H:%M:%SZ")
##      shell: bash
##    - name: clcache cache files
##      uses: actions/cache@v2
##      with:
##        path: ~/clcache
##        key: ${{ runner.os }}-msvc-clcache-${{ steps.get-timestamp.outputs.timestamp }}
##        restore-keys: ${{ runner.os }}-msvc-clcache-
#oo
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    - name: dev cmd
      uses: ilammy/msvc-dev-cmd@v1
    - name: test cl.exe
      run: |
        cl.exe
      shell: bash
    - name: qtest
      run: |
        cd qtest
        qmake -project "QT += testlib"
        qmake
        nmake
      shell: bash
