# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: ./.github/actions/download-qt
      with:
        toolchain: win64_msvc2019_64
#    - name: Install Qt Creator
#      uses: ./.github/actions/download-qtc
#    - name: Setup Qbs
#      run: |
#        qbs setup-toolchains --detect
#        qbs setup-qt $(which qmake).exe qt
#        qbs config defaultProfile qt
#        qbs config --list
#      shell: bash
    - name: create project
      run: |
        mkdir qt
        cd qt
        echo >application.pro <<EOT
        QT += widgets
        requires(qtConfig(filedialog))

        HEADERS       = mainwindow.h
        SOURCES       = main.cpp \
                        mainwindow.cpp
        #! [0]
        RESOURCES     = application.qrc
        #! [0]

        # install
        target.path = $$[QT_INSTALL_EXAMPLES]/widgets/mainwindows/application
        INSTALLS += target
        EOT
        ls -la
        cat  application.pro
      shell: bash
    
