# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: make changes
      run: |
        set -x
        sudo /etc/init.d/mono-xsp4 status
        xsp4 --version
        sudo cat /etc/default/mono-xsp4
        sudo systemctl show -p ActiveState --value mono-xsp4
        
    - name: status
      shell: pwsh
      run: |
        ((/etc/init.d/mono-xsp4 status) | Select-Object -index 2).Split(' ')[6]
        ((/etc/init.d/mono-xsp4 status) | Select-Object -index 2).Split(' ')[7]
