# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.3.9
    
    - name: mvn --version with M2
      run: |
        set -x
        ls -l `which mvn`
        cat `which mvn`
        mvn --version
        
    - name: mvn --version without M2
      run: |
        set -x
        ls -l `which mvn`
        cat `which mvn`
        unset M2_HOME
        mvn --version
        
