# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: make changes
      run: |
        cat /etc/apt/sources.list > /tmp/1 
        ls -la /etc/apt/sources.list.d > /tmp/2
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:hvr/ghc
        cat /etc/apt/sources.list > /tmp/3
        ls -la /etc/apt/sources.list.d > /tmp/4
        diff /tmp/1 /tmp/3
        diff /tmp/2 /tmp/4
