# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
      # 将 semantic 输出的值作为下一环节的输入
      # semantic: ${{ toJSON(steps.semantic.outputs) }} # ! MUST BE STRING

jobs:
  check:
    name: Code quality check
    runs-on: ubuntu-latest 
    outputs:
        semantic: ${{ toJSON(steps.semantic.outputs) }} 
    steps: 
      - uses: actions/checkout@v2
      - name: Semantic Release with dryRun
        id: semantic
        run: |
            echo '::set-output name=result::true'

# This workflow contains a single job called "build"
  build:
    needs: check
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Tricky version
      run: |
        echo "AAA"
        echo ${{ needs.check.outputs.semantic }}  
        echo "==="
        # echo ${{ fromJSON(needs.check.outputs.semantic).result }}  
        echo "BBB"  
 
