# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-latest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: google-chrome-stable
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -c google-chrome-stable_current_amd64.deb
        
    - name: yarn
      run: |
        cat /etc/apt/sources.list.d/yarn.list
        #ls -l /var/lib/apt/lists/
        #grep ^Package /var/lib/apt/lists/dl.yarnpkg.com_debian_dists_stable*
        sudo apt-get purge yarn
        sudo rm /etc/apt/sources.list.d/yarn.list
        sudo apt-get update
        sudo npm install -g yarn
        yarn --version
