name: Swift

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 11.7

      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: Bundle Install
        env:
          BUNDLE_FROZEN: "true"
        run: |
          which ruby
          which gem
          gem env
          find /Users/runner/hostedtoolcache/ -name bundle || true
          find /Users/runner/hostedtoolcache/ -name bundler
          bundle install
