# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: show disk info
      run: |
        pwd
        diskutil info -all
    
    - name: build mksparse
      run: |
        gcc mksparse.c -o mksparse
        ./mksparse 
        ls -ls
        mv file.hole /tmp/f.hole
        mv file.nohole /tmp/f.nohole
        ls -ls /tmp/f.*

    - name: tar
      run: |
        for i in {1..100}; do
           echo "Attempt $i"
           test -f file.hole && rm file.hole
           ./mksparse 
           ls -ls file.hole
           mv file.hole /tmp/bin1
           test -f file.hole && rm file.hole
           ./mksparse 
           ls -ls file.hole
           mv file.hole /tmp/bin2
           ls -ls /tmp/bin?
           shasum /tmp/bin1 /tmp/bin2 > /tmp/check
           tar  -czvf /tmp/arc.tgz /tmp/bin1 /tmp/bin2
           mkdir /tmp/x
           pushd /tmp/x
           tar -xzf /tmp/arc.tgz
           shasum -c /tmp/check || exit
           popd
           rm -rf /tmp/x
        done



