# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        #        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    
    runs-on: ${{ matrix.os }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: restore llvm repos
      run: |
        LSB_RELEASE=$(lsb_release -rs)
        wget https://packages.microsoft.com/config/ubuntu/$LSB_RELEASE/packages-microsoft-prod.deb
        dpkg -x packages-microsoft-prod.deb /tmp/x
        ls -la /tmp/x/etc
        ls -la /tmp/x/etc/apt
        cat etc/apt/sources.list
